/*- table should contain numeric, string, datetime columns*/
CREATE TABLE BRANCH(
  Branch_No INTEGER PRIMARY KEY,
  Address VARCHAR2(30),
  Tel_No VARCHAR2(30),
  FAX_No VARCHAR2(30)
);

/*create script that adds comments to table and each column*/
COMMENT ON TABLE BRANCH IS 'Company branch.';
COMMENT ON COLUMN BRANCH.Address IS 'Physical branch address';

/*create index over one column, several columns*/
CREATE INDEX BRANCH_ADDRESS_INDEX ON BRANCH(Address)
  TABLESPACE YOUR_HOME
  STORAGE (INITIAL 20K NEXT 20k PCTINCREASE 75);

/*create script what adds constraints, both reference and check constraints*/
ALTER TABLE BRANCH
  ADD CONSTRAINT BRANCH_UNIQUE_TEL UNIQUE (Tel_No);

/*FIXME Is it actually what do we need!?*/
ALTER TABLE STAFF
  ADD CONSTRAINT REFERENCE_CONSTRAINT
  FOREIGN KEY (Branch_No)
  REFERENCES BRANCH;

ALTER TABLE BRANCH
  ADD CONSTRAINT BRANCH_ADDRESS_CHECK_CONST CHECK (Address != 'Russia');

CREATE TABLE STAFF(
  Staff_No INTEGER PRIMARY KEY,
  Name VARCHAR2(30),
  Tel_No VARCHAR2(30),
  Sex VARCHAR2(30),
  DOB DATE,
  Position VARCHAR2(30),
  Salary NUMERIC(8,2), /*NUMERIC(precision, scale) NUMERIC(8,2) - 1000000.00*/
  Date_Joined DATE,
  Branch_No INTEGER
);

/*create temporary table*/
CREATE TEMPORARY TABLESPACE YOUR_HOME_TEMP
  TEMPFILE 'tbs_t1.f' SIZE 50m REUSE AUTOEXTEND ON
  MAXSIZE UNLIMITED
  EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K;

CREATE GLOBAL TEMPORARY TABLE YOUR_HOME_TEMP.TEMP_TABLE
(
  id INTEGER PRIMARY KEY
);

/*create cluster based table*/
DROP TABLE BRANCH CASCADE CONSTRAINTS;
DROP TABLE STAFF CASCADE CONSTRAINTS;

CREATE CLUSTER BRANCH_STAFF
  (Branch_No INTEGER)
TABLESPACE YOUR_HOME
SIZE 512;

CREATE INDEX IDX_BRANCH_STAFF_CLUSTER ON CLUSTER BRANCH_STAFF;

CREATE TABLE BRANCH(
  Branch_No INTEGER PRIMARY KEY,
  Address VARCHAR2(30),
  Tel_No VARCHAR2(30),
  FAX_No VARCHAR2(30)
)CLUSTER BRANCH_STAFF Branch_No;

CREATE TABLE STAFF(
  Staff_No INTEGER PRIMARY KEY,
  Name VARCHAR2(30),
  Tel_No VARCHAR2(30),
  Sex VARCHAR2(30),
  DOB DATE,
  Position VARCHAR2(30),
  Salary NUMERIC(8,2),
  Date_Joined DATE,
  Branch_No INTEGER
)CLUSTER BRANCH_STAFF Branch_No;