connect sys as sysdba
@?/demo/schema/human_resources/hr_main.sql

SELECT       table_name FROM user_tables;

SELECT * FROM EMPLOYEES
	WHERE DEPARTMENT_ID = 90;

SELECT DEPARTMENT_NAME, FIRST_NAME, PHONE_NUMBER, SALARY
FROM HR.DEPARTMENTS D JOIN HR.EMPLOYEES E ON (D.MANAGER_ID=E.EMPLOYEE_ID)
	WHERE DEPARTMENT_ID = 90;