CREATE TABLESPACE TBLSPCMYONE
	DATAFILE 'C:\OracleDatabase\app\oracle\oradata\xe\ONE.dat' SIZE 100M REUSE
	AUTOEXTEND ON NEXT 2M MAXSIZE 200M;

SELECT tablespace_name, file_name, status, bytes
FROM dba_data_files
WHERE tablespace_name LIKE 'TBLSP%'
ORDER BY tablespace_name, file_name
/

CREATE USER Admin1 IDENTIFIED BY Admin1
DEFAULT TABLESPACE TBLSPCMYONE
/

GRANT CREATE SESSION TO Admin1 /*назначается из-под System*/

connect Admin1/Admin1

connect System/root@xe

SELECT USERNAME, USER_ID, PASSWORD, ACCOUNT_STATUS, DEFAULT_TABLESPACE,
TEMPORARY_TABLESPACE, PROFILE
FROM DBA_USERS
WHERE USERNAME = 'Admin1' /*просмотр информации об пользователе*/
/

/*назначение прав пользователю*/
/*на создание объектов БД*/
GRANT CREATE TABLE TO Admin1
/
GRANT CREATE PROCEDURE TO Admin1
/
GRANT CREATE TRIGGER TO Admin1
/
GRANT CREATE VIEW TO Admin1
/
GRANT CREATE SEQUENCE TO Admin1
/

/*на изменение объектов*/
GRANT ALTER ANY TABLE TO Admin1
/
GRANT ALTER ANY PROCEDURE TO Admin1
/
GRANT ALTER ANY TRIGGER TO Admin1
/
GRANT ALTER PROFILE TO Admin1
/

/*на удаление объектов*/
GRANT DELETE ANY TABLE TO Admin1
/
GRANT DROP ANY TABLE TO Admin1
/
GRANT DROP ANY PROCEDURE TO Admin1
/
GRANT DROP ANY TRIGGER TO Admin1
/
GRANT DROP ANY VIEW TO Admin1
/
GRANT DROP ANY PROFILE TO Admin1
/

connect System/root@xe

GRANT UNLIMITED TABLESPACE TO Admin1

connect Admin1/Admin1

CREATE TABLE TESTTABLE
(
	TEST_NUMERIC NUMBER PRIMARY KEY,
	TEST_STRING VARCHAR2(10),
	TEST_DATE DATE
)
/

COMMENT ON TABLE TESTTABLE IS 'It is comment';

COMMENT ON COLUMN TESTTABLE.TEST_NUMERIC IS 'Numeric comment';
COMMENT ON COLUMN TESTTABLE.TEST_STRING IS 'String comment';
COMMENT ON COLUMN TESTTABLE.TEST_DATE IS 'Date comment';

CREATE INDEX test_string_index ON TESTTABLE(TEST_STRING)
TABLESPACE TBLSPCMYONE
STORAGE (INITIAL 20K NEXT 20k PCTINCREASE 75);

CREATE INDEX test_date_index ON TESTTABLE(TEST_DATE)
TABLESPACE TBLSPCMYONE
STORAGE (INITIAL 20K NEXT 20k PCTINCREASE 75);

ALTER TABLE TESTTABLE MODIFY(TEST_DATE NOT NULL);
ALTER TABLE TESTTABLE ADD CONSTRAINT string_unique UNIQUE(TEST_STRING);
ALTER TABLE TESTTABLE ADD CONSTRAINT date_check CHECK(TEST_DATE >= date '2013-01-01');

select table_name from user_constraints where constraint_name = 'DATE_CHECK';

CREATE TABLE TESTRELATEDTABLE
(
	TEST_RELATED_NUMERIC NUMBER PRIMARY KEY,
	TEST_RELATED_STRING VARCHAR2(10),
	TEST_RELATED_DATE DATE
)
/

ALTER TABLE TESTRELATEDTABLE
ADD CONSTRAINT foreign_key
FOREIGN KEY(TEST_RELATED_NUMERIC)
REFERENCES TESTTABLE;

/*
ALTER TABLE имя_подчиненной_таблицы
ADD CONSTRAINT имя_ограничения
FOREIGN KEY (имена_столбцов_подчиненной_таблицы)
REFERENCES имя_главной_таблицы;
*/

CREATE GLOBAL TEMPORARY TABLE ADMIN1.TEMP_TABLE
(
	ID NUMBER,
	DNAME VARCHAR2(10)
)
/

CREATE CLUSTER emp_dept (deptno NUMBER(3))
   SIZE 600
   TABLESPACE TBLSPCMYONE
   STORAGE (INITIAL 200K
      NEXT 300K
      MINEXTENTS 2
      PCTINCREASE 33);

CREATE TABLE dept (
   deptno NUMBER(3) PRIMARY KEY)
   CLUSTER emp_dept (deptno);

CREATE TABLE emp (
   empno NUMBER(5) PRIMARY KEY,
   ename VARCHAR2(15) NOT NULL,
   deptno NUMBER(3) REFERENCES dept)
   CLUSTER emp_dept (deptno);

/* -------------------------------------Task number 4---------------------------------------------*/

insert info TESTTABLE(TEST_NUMERIC, TEST_STRING, TEST_DATE)
   VALUES(200, 'string', TO_DATE('2013/05/03 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));


select TEST_NUMERIC, TEST_STRING, TEST_DATE
   from TESTTABLE
   WHERE TEST_NUMERIC = 200;


ALTER TABLE TESTTABLE
   ADD new_col CHAR(25);

ALTER TABLE TESTTABLE
   ADD col_with_defvalue CHAR(25) DEFAULT 'this is def value' NOT NULL;

ALTER TABLE TESTTABLE
   MODIFY new_col char(25) not NULL;

ALTER TABLE TESTTABLE
   RENAME COLUMN new_col TO sales;

ALTER TABLE TESTTABLE
   DROP COLUMN sales;

ALTER TABLE TESTTABLE
   MODIFY col_with_defvalue DEFAULT NULL;

ALTER TABLE TESTTABLE
   DISABLE CONSTRAINT string_unique