CREATE USER valerius
    IDENTIFIED BY admin
    DEFAULT TABLESPACE LABS
    QUOTA 30M ON LABS;

GRANT CREATE SESSION TO valerius;

GRANT CREATE TABLE TO valerius;

GRANT CREATE SEQUENCE TO valerius;

--GRANT ALTER ON test TO valerius;