connect sys as sysdba
@?/demo/schema/human_resources/hr_main.sql

SELECT table_name FROM user_tables;


SELECT FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER
FROM EMPLOYEES;

SELECT * FROM EMPLOYEES
	WHERE DEPARTMENT_ID = &DEPARTMENT_ID;

SELECT DEPARTMENT_NAME, FIRST_NAME, PHONE_NUMBER, SALARY
FROM HR.DEPARTMENTS D JOIN HR.EMPLOYEES E ON (D.MANAGER_ID!=E.EMPLOYEE_ID)
ORDER BY DEPARTMENT_NAME, SALARY desc;



