CREATE TABLE SCHEDULE_ADMIN.UNIVERSITY_BUILDING(
  BUILDING_ID INTEGER PRIMARY KEY,
  STREET VARCHAR2(30) NOT NULL,
  BUILDING VARCHAR2(30),
  BUILD_NUMBER VARCHAR2(30) NOT NULL
)TABLESPACE SCHEDULE_TABLESPACE;

COMMENT ON TABLE SCHEDULE_ADMIN.UNIVERSITY_BUILDING IS 'The table where store list of university buildings';

COMMENT ON COLUMN SCHEDULE_ADMIN.UNIVERSITY_BUILDING.BUILDING IS 'It is korpus!';

CREATE INDEX SCHEDULE_ADMIN_STREET_INDEX ON SCHEDULE_ADMIN.UNIVERSITY_BUILDING(STREET);

ALTER TABLE SCHEDULE_ADMIN.UNIVERSITY_BUILDING
  ADD CONSTRAINT TEMP_UNIQUE_NUMBER UNIQUE (BUILDING);


CREATE TEMPORARY TABLESPACE SCHEDULE_ADMIN_TEMP TEMPFILE 'temp.dat' SIZE 50m REUSE AUTOEXTEND ON MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL UNIFORM SIZE 64K;

/*FINISH'N'UNDERSTAND CLUSTERS. */