CREATE TABLESPACE MY_TABLESPACE
	DATAFILE 'C:\oraclexe\app\oracle\oradata\XE\my_datafile.dat' SIZE 100M REUSE
	AUTOEXTEND ON NEXT 2M MAXSIZE 200M;

CREATE USER Admin IDENTIFIED BY Admin
DEFAULT TABLESPACE MY_TABLESPACE;

GRANT CREATE SESSION TO Admin;

SELECT USERNAME, USER_ID, PASSWORD, ACCOUNT_STATUS, DEFAULT_TABLESPACE,
TEMPORARY_TABLESPACE, PROFILE
FROM DBA_USERS
WHERE USERNAME = 'Admin';

GRANT CREATE TABLE TO Admin;
GRANT CREATE PROCEDURE TO Admin;
GRANT CREATE TRIGGER TO Admin;
GRANT CREATE VIEW TO Admin;
GRANT CREATE SEQUENCE TO Admin;

GRANT ALTER ANY TABLE TO Admin;
GRANT ALTER ANY PROCEDURE TO Admin;
GRANT ALTER ANY TRIGGER TO Admin;
GRANT ALTER PROFILE TO Admin;

GRANT DELETE ANY TABLE TO Admin;
GRANT DROP ANY TABLE TO Admin;
GRANT DROP ANY PROCEDURE TO Admin;
GRANT DROP ANY TRIGGER TO Admin;
GRANT DROP ANY VIEW TO Admin;
GRANT DROP ANY PROFILE TO Admin;

GRANT UNLIMITED TABLESPACE TO Admin

CREATE TABLE MY_TABLE
(
	NUM NUMBER PRIMARY KEY,
	STR VARCHAR2(10),
	DATE DATE
);

COMMENT ON TABLE MY_TABLE IS 'Hello, World';

COMMENT ON COLUMN MY_TABLE.NUM IS 'It is a number';
COMMENT ON COLUMN MY_TABLE.STR IS 'Is is a string';
COMMENT ON COLUMN MY_TABLE.DATE IS 'Is is a date';

CREATE INDEX str_index ON MY_TABLE(STR)
TABLESPACE MY_TABLESPACE
STORAGE (INITIAL 20K NEXT 20k PCTINCREASE 75);

CREATE INDEX date_index ON TESTTABLE(DATE)
TABLESPACE MY_TABLESPACE
STORAGE (INITIAL 20K NEXT 20k PCTINCREASE 75);

ALTER TABLE MY_TABLE MODIFY(DATE NOT NULL);
ALTER TABLE MY_TABLE ADD CONSTRAINT unique_str UNIQUE(STRING);
ALTER TABLE MY_TABLE ADD CONSTRAINT date_check CHECK(DATE >= date '2012-12-22');

CREATE TABLE MY_RELATED_TABLE
(
	RELATED_NUM NUMBER PRIMARY KEY,
	RELATED_STR VARCHAR2(10),
	RELATED_DATE DATE
);

ALTER TABLE MY_RELATED_TABLE
ADD CONSTRAINT foreign_key
FOREIGN KEY(RELATED_NUM)
REFERENCES MY_TABLE

CREATE GLOBAL TEMPORARY TABLE ADMIN.TEMP_TABLE
(
	ID NUMBER,
	DNAME VARCHAR2(10)
);

CREATE CLUSTER my_cluster (cluster_num NUMBER(3))
   SIZE 600
   TABLESPACE MY_TABLESPACE
   STORAGE (INITIAL 200K
      NEXT 300K
      MINEXTENTS 2
      PCTINCREASE 33);

CREATE TABLE dept (
   cluster_num NUMBER(3) PRIMARY KEY)
   CLUSTER my_cluster (cluster_num);

CREATE TABLE emp (
   empno NUMBER(5) PRIMARY KEY,
   ename VARCHAR2(15) NOT NULL,
   cluster_num NUMBER(3) REFERENCES dept)
   CLUSTER my_cluster (cluster_num);

insert into MY_TABLE(NUM, STR, DATE)
   VALUES(200, 'string', TO_DATE('2012/12/22 21:02:44', 'yyyy/mm/dd hh24:mi:ss'));


select NUM, STR, DATE
   from MY_TABLE
   WHERE NUM = 200;


ALTER TABLE MY_TABLE
   ADD new_col CHAR(25);

ALTER TABLE MY_TABLE
   ADD col_with_defvalue CHAR(25) DEFAULT 'default value' NOT NULL;

ALTER TABLE MY_TABLE
   MODIFY new_col char(25) not NULL;

ALTER TABLE MY_TABLE
   RENAME COLUMN new_col TO sales;

ALTER TABLE MY_TABLE
   DROP COLUMN sales;

ALTER TABLE MY_TABLE
   MODIFY col_with_defvalue DEFAULT NULL;

ALTER TABLE MY_TABLE
   DISABLE CONSTRAINT string_unique

RENAME MY_TABLE to MY_TABLE_bak

CREATE TABLE MY_TABLE as (select * from MY_TABLE_bak)
