CREATE USER yourhome
  IDENTIFIED BY yourhome
  DEFAULT TABLESPACE YOUR_HOME
  QUOTA UNLIMITED ON YOUR_HOME;

GRANT CREATE SESSION TO YOURHOME;
GRANT CREATE TABLE TO YOURHOME;
GRANT CREATE PROCEDURE TO YOURHOME;
GRANT CREATE TRIGGER TO YOURHOME;
GRANT CREATE VIEW TO YOURHOME;
GRANT CREATE SEQUENCE TO YOURHOME;
GRANT CREATE CLUSTER TO YOURHOME;

GRANT ALTER ANY TABLE TO YOURHOME;
GRANT ALTER ANY PROCEDURE TO YOURHOME;
GRANT ALTER ANY TRIGGER TO YOURHOME;
GRANT ALTER PROFILE TO YOURHOME;

GRANT DELETE ANY TABLE TO YOURHOME;
GRANT DROP ANY TABLE TO YOURHOME;
GRANT DROP ANY PROCEDURE TO YOURHOME;
GRANT DROP ANY TRIGGER TO YOURHOME;
GRANT DROP ANY VIEW TO YOURHOME;
GRANT DROP PROFILE TO YOURHOME;